### ISSUE TITLE
default format for nginx.conf should parse as nginx

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/fluentd-catch-all-config#10]
The default log formats for google fluentd access logs currently has 'format none':
[https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/blob/master/configs/config.d/nginx.conf#L3](https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/blob/master/configs/config.d/nginx.conf#L3)

This shows up simply as a TextPayload logline in cloud-logging.

However, if you specify 'format nginx', its parsed as JSONStruct in cloud logging:
[http://docs.fluentd.org/articles/common-log-formats](http://docs.fluentd.org/articles/common-log-formats)

Please update nginx access and error log formats configs.

**Comment by chaintng** [comment]
With that format, it push log as `jsonPayload`
Which is still not nice, we should record it as `httpRequest` class in the log.
This could be done in log v1 via this https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/57
But not sure how to do it in v2

**Comment by igorpeshansky** [comment]
@chaintng You'd do it the same way — that code was ported to v2.

**Comment by chaintng** [comment]
Thanks @igorpeshansky for very fast response! 👍 
I tried format it like this (below link)
But i still not getting what i expected (in the picture)

http://fluentular.herokuapp.com/parse?regexp=%5E%28%3F%3ChttpRequest%3E%28%3F%3Cremote%3E%5B%5E+%5D*%29+%28%3F%3Chost%3E%5B%5E+%5D*%29+%28%3F%3Cuser%3E%5B%5E+%5D*%29+%5C%5B%28%3F%3Ctime%3E%5B%5E%5C%5D%5D*%29%5C%5D+%22%28%3F%3Cmethod%3E%5CS%2B%29%28%3F%3A+%2B%28%3F%3Cpath%3E%5B%5E%5C%22%5D*%29+%2B%5CS*%29%3F%22+%28%3F%3Ccode%3E%5B%5E+%5D*%29+%28%3F%3Csize%3E%5B%5E+%5D*%29%28%3F%3A+%22%28%3F%3Creferer%3E%5B%5E%5C%22%5D*%29%22+%22%28%3F%3Cagent%3E%5B%5E%5C%22%5D*%29%22%29%3F+%28%3F%3Crequest_time%3E%5B%5E+%5D*%29+%28%3F%3Cupstream_time%3E%5B%5E+%5D*%29+%28%3F%3Cpipe%3E%5B%5E+%5D*%29%29%24&input=130.211.1.60+-+-+%5B07%2FApr%2F2017%3A02%3A23%3A59+%2B0000%5D+%22GET+%2Fhealthy-check+HTTP%2F1.1%22+200+25+%22-%22+%22GoogleHC%2F1.0%22+0.885+0.885+.&time_format=%25d%2F%25b%2F%25Y%3A%25H%3A%25M%3A%25S+%25z

![image](https://cloud.githubusercontent.com/assets/2979072/24783872/2a0766fe-1b79-11e7-9907-c8e5dd7e0d29.png)

**Comment by igorpeshansky** [comment]
@chaintng The 'httpRequest' payload field has to be a structured JSON object, as in the code you've pointed to. The `nginx` format parsing could produce that, but we need to document exactly how.

**Comment by chaintng** [comment]
Understood, seem like i can structured `jsonPayload` but not sure how to make it as `httpRequest` so the View UI can show it more nice. Waiting for document :) Thank you so much.

**Comment by chaintng** [comment]
Oh, i just realize that i can custom nginx log... So i can manage to make it work now.

Is there anyway i can contribute to the document ?

**Comment by igorpeshansky** [comment]
Unfortunately, not at this time -- our documentation is not on any publicly-editable web site -- but thanks for the offer.

**Comment by kdabir** [comment]
@chaintng How did you create the nesting required for achieving the structure

```
jsonPayload: {
   httpRequest: {
      ...
   }
}
```

I want to send `operation` and `httpRequest` objects, both of them require nesting.

**Comment by chaintng** [comment]
Hi @kdabir ,

Here is the sample nginx config

```
    log_format json_combined escape=json '{ "httpRequest": {'
        '"requestMethod": "$request_method", '
        '"requestUrl": "$request_uri", '
        '"responseSize": "$bytes_sent", '
        '"status": "$status", '
        '"userAgent": "$http_user_agent", '
        '"remoteIp": "$remote_addr", '
        '"referer": "$http_referer", '
        '"host": "$host", '
        '"requestTime": "$request_time", '
        '"upstreamResponseTime": "$upstream_response_time" }, '
        '"time": "$time_local" }';
```

**Comment by chaintng** [comment]
And what `operation` do? can you direct me to the docs please?

**Comment by kdabir** [comment]
@chaintng Ah I see, you update nginx config to generate json. thats cool. Thanks. 

For `operation`, see here: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogEntryOperation

It supposedly connects multiple log statement that are logically part of some operation using an id, like requestId. However, It is not working with google-fluentd plugin so far. I have raised an issue here:

https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/126

**Comment by philss** [comment]
for me the only change needed was in `format` that I changed from `none` to `nginx` (only for nginx access). It worked.

**Comment by jrynyt** [comment]
With nginx logging json to a file in the format suggested above, tailed by fluentd, the only way I could get it to work was with `format none` and google-fluentd configured with `detect_json true`. `format json` did not work -- there were no warnings in google-fluentd.log, but the logs simply did not show up in stackdriver. It would be good to document exactly how google-fluentd and stackdriver work together.

**Comment by fred-jan** [comment]
It seems like `format: nginx` will make sure the log data (in default nginx format) is parsed into a jsonPayload correctly.

Furthermore i stumbled upon some interesting behavior: when i change the source tag to `nginx-access` (instead of the `nginx.access` I've been using so far) it causes the log entries to be semantically interpreted as http requests and show up nice in the UI like this:

![image](https://user-images.githubusercontent.com/2146611/39048366-7b7dbe9a-449d-11e8-8b6c-508402ef3223.png)

**Comment by salrashid123** [comment]
`format: nginx` and `apache2` is setup now by default if you enable the `--structured` flag in the installer

```bash
root@instance-1:~# curl -sSO "https://dl.google.com/cloudagents/install-logging-agent.sh"
root@instance-1:~# bash install-logging-agent.sh --structured

==============================================================================
Starting installation of google-fluentd
==============================================================================

Installing agents for Debian or Ubuntu.
OK
Selecting previously unselected package google-fluentd.
(Reading database ... 33997 files and directories currently installed.)
Preparing to unpack .../google-fluentd_1.6.1-1_amd64.deb ...
Unpacking google-fluentd (1.6.1-1) ...
Selecting previously unselected package google-fluentd-catch-all-config-structured.
Preparing to unpack .../google-fluentd-catch-all-config-structured_1.0_all.deb ...
Unpacking google-fluentd-catch-all-config-structured (1.0) ...
Setting up google-fluentd (1.6.1-1) ...
Adding system user `google-fluentd' (UID 108) ...
Adding new group `google-fluentd' (GID 112) ...
Adding new user `google-fluentd' (UID 108) with group `google-fluentd' ...
Not creating home directory `/home/google-fluentd'.
Installing default conffile /etc/google-fluentd/google-fluentd.conf ...
Setting up google-fluentd-catch-all-config-structured (1.0) ...

root@instance-1:~# more /etc/google-fluentd/config.d/nginx.conf 
<source>
  @type tail
  format nginx
  path /var/log/nginx/access.log
  pos_file /var/lib/google-fluentd/pos/nginx-access.pos
  read_from_head true
  tag nginx-access
</source>

<source>
  @type tail
  format none
  path /var/log/nginx/error.log
  pos_file /var/lib/google-fluentd/pos/nginx-error.pos
  read_from_head true
  tag nginx-error
</source>
```

**Comment by JayTeli** [comment]
@chaintng : What fluentd source config did you use when nginx access logs used json logging format. Please help  with https://github.com/fluent/fluentd/issues/2439

**Comment by igorpeshansky** [comment]
@JayTeli, please don't hijack an unrelated issue on an unrelated project. This issue is about adding the default NGINX log format to the configuration for the Stackdriver logging agent ([google-fluentd](http://github.com/GoogleCloudPlatform/google-fluentd)). You are asking about parsing a separate, custom log format.
If your question is about configuring the base fluentd, then fluent/fluentd#2439 is the right place to ask. If you are trying to ingest those logs specifically into Stackdriver, then please create another issue in the [google-fluentd](http://github.com/GoogleCloudPlatform/google-fluentd) repository.

**Comment by JayTeli** [comment]
It was a related issue of fluentd. If you couldnt understand it then doesnt
give u the right to call u unrelated. I am working on fluentd and posted it
on fluentd repo. If u cannot help , please dont waste my time. I closed
#2439 by help from a friend , since you guys didnt respond on time.
I closed issue myself , doesnt mean i was wrong about something.
Documentation is not up to the mark and so weface such concerns.

**Comment by igorpeshansky** [comment]
> You are asking about parsing a separate, custom log format.

You are also conflating https://github.com/fluent/fluentd, which is a project/repo owned and maintained by Treasure Data, and the repos related to the (Google) Stackdriver logging agent, google-fluentd, which is a repackaging of base fluentd with Stackdriver-specific configs (this repo). As I said in my message, this is not the right place to ask your question, as this repo (and this issue) has nothing to do with the question you're asking. I attempted to route you to the right repo for your question, depending on your exact use case.
The fluentd documentation, maintained by Treasure Data, is at https://docs.fluentd.org/ .
The Stackdriver logging agent documentation, maintained by Google, is at https://cloud.google.com/logging/docs/agent .
