### ISSUE TITLE
'type' is deprecated parameter name. use '@type'

### ISSUE THREAD

**Issue by kdabir** [GoogleCloudPlatform/fluentd-catch-all-config#13]
We are seeing bunch of warnings because of catch-all config uses `type` instead of `@type`

`[warn]: 'type' is deprecated parameter name. use '@type' instead.`

If required I can send a PR with updated param.

**Comment by kdabir** [comment]
Oops, I saw this PR just now (https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/pull/11). Hope it gets merged soon.

**Comment by qingling128** [comment]
Addressed in https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/pull/15. Closing.
