### ISSUE TITLE
redis is the only third party in the centminmod

### ISSUE THREAD

**Issue by aelsharawi** [GoogleCloudPlatform/fluentd-catch-all-config#14]
I don't see any log apart from the redis, nginx error,access is not there

**Comment by igorpeshansky** [comment]
More info, please. Where are the nginx error and access logs stored on your system?

**Comment by aelsharawi** [comment]
I'm talking about google cloud stackdriver logger, doesn't show Nginx logs on the interface

**Comment by igorpeshansky** [comment]
Ok, we'll need a lot more detail than that. Are you installing the Stackdriver logging agent on a GCE or EC2 VM? Or are you using the `fluentd-gcp` container on Kubernetes/GKE? Or are you using the gem directly in some other setup?
If you're on GCE/EC2, the logging agent looks for the logs in specific locations by default. If your logs are not in one of those locations, it won't find them.

**Comment by aelsharawi** [comment]
I'm on GCE, and centminmod.com is not having the default Nginx log location, how to fix that on stack driver logger?

**Comment by igorpeshansky** [comment]
Ah. Simple: you add a file, e.g., `centminmod-nginx.conf`, to `/etc/google-fluentd/config.d`, with the contents of [the default nginx config](https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/blob/master/configs/config.d/nginx.conf), but with `/var/log/nginx/` replaced by where your server stores its logs. See http://docs.fluentd.org/v0.14/articles/in_tail for more info.
In any case, this is working as intended.

**Comment by aelsharawi** [comment]
thanks a lot for help, it worked
