### ISSUE TITLE
Support auditd log parsing

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/fluentd-catch-all-config#25]
Feature request to support [auditd](https://linux.die.net/man/8/auditd) logs.

While auditd is listed in [fluentd catalog of plugins](https://www.fluentd.org/plugins) the links leads to a repo that isn't populated anymore (its empty).

Her'es is a [sample auditd parser](https://medium.com/google-cloud/auditd-agent-config-for-stackdriver-logging-c27d1431ed3a) i wrote for which uses `kv` that could be used here too.

**Comment by jkohen** [comment]
@salrashid123 from recent conversations, I believe you have a solution for this. Please reopen if needed.
