### ISSUE TITLE
 fluentd-catch-all-config/configs/config.d/syslog_endpoint.conf causing fluent to listen on 514

### ISSUE THREAD

**Issue by faithseed** [GoogleCloudPlatform/fluentd-catch-all-config#8]
fluentd-catch-all-config/configs/config.d/syslog_endpoint.conf is causing the fluentd to listen on TCP/UDP 514

Why does it need to be there? We have a rsyslogd setup to listen on UDP 514. This is conflicting with fluentd and causing the google-fluentd to flap from time to time.

The question is why does it need to be there in the first place?

**Comment by faithseed** [comment]
https://dl.google.com/cloudagents/install-logging-agent.sh we are using this script to install the logging agent on GCE and it is impossible to add ENV DO_NOT_INSTALL_CATCH_ALL_CONFIG.

**Comment by faithseed** [comment]
any update

**Comment by jkohen** [comment]
I'm cleaning up old issues. A simple workaround would be to delete that configuration file.

I'm not sure why you can't add the environment variable on GCE. Can you run the script as `env DO_NOT_INSTALL_CATCH_ALL_CONFIG=true install-logging-agent.sh`?

Please reopen if you still need assistance.
